### ISSUE TITLE
UID and GID in Docker compose and env files assume, that installation is done with user with id 1000

### ISSUE THREAD

**Issue by knurd75zid** [tcpipuk/tcpipuk.github.io#15]
First let me thank you for all the valuable work you have done with this documentation. I learned so much from it and I was not even successful yet. :) 

The first Issue I ran into was, that the documentation assumes, that uid and gid are 1000.
That is only the case for the very first unprivileged User in a debian system, for example.
In my well used and mangled docker host, this is not the case. I make a new user for a new project and try to cultivate the habit of not working too much as root if not necessary. 
Maybe a text should be added, to make that a bit clearer?
This concernes the docker compose and the .synapse.env file, as far as I am aware.

**Comment by tcpipuk** [comment]
Hello! You make a good point, but would you suggest any changes to the config itself, or simply to tell people that they should change the uid:gid if they are using a different user?

**Comment by knurd75zid** [comment]
I thought, the latter. Just a note, that the "1000" should be changed to uid:gid of the actual user installing matrix.

**Comment by tcpipuk** [comment]
It doesn't really need to be "the actual user installing matrix" but more we need the sockets/etc to be owned by the same UID between containers so they can all speak to each other.

Putting a little disclaimer in would save people blaming me, but doesn't really feel like it's solving the problem... I could use some arbitrary high number, but that might result in a similar issue if someone has many thousands of users?

**Comment by tcpipuk** [comment]
No response in months, going to leave it as-is!
