### ISSUE TITLE
homeserver.yaml and other files not accessible in rootless docker setup on debian 12 bookworm

### ISSUE THREAD

**Issue by knurd75zid** [tcpipuk/tcpipuk.github.io#16]
I hope I am not a nuissance yet, but you said to report issues with the documentation. I always assume, it might be my mistake, but I can't figure out yet what I might have done wrong.

tl;dr
The docker command to create the configs and the key leave me with inaccessible files and directories, in the rootless docker config on debian 12.

Steps I have taken.
To have the best chance of success, I reinstalled a fresh, debian 12 machine, and added the user matrix as the first non privileged user.
This user has uid:gid 1000:1000. Then I created the config files (docker-compose.yml and the two .env files) as per your instructions and started the docker with the command provided in your docs, to create the necessary files and directories.

I ended up with this:
```
matrix@docker:~$ ls -l
total 32
drwxr-xr-x  4 matrix matrix 4096 Apr 24 12:52 AMdotfiles
-rw-r--r--  1 matrix matrix 2284 Apr 24 15:00 docker-compose.yml
drwxr-xr-x  2 matrix matrix 4096 Apr 24 15:02 logs
drwxr-xr-x  2 matrix matrix 4096 Apr 24 15:02 media
drwx------ 19 100069 matrix 4096 Apr 24 15:02 pgsql16
drwxr-xr-x  2 matrix matrix 4096 Apr 24 15:01 redis
drwxr-xr-x  3 matrix matrix 4096 Apr 24 12:47 ssl
drwxr-xr-x  3 100999 100999 4096 Apr 24 15:02 synapse
```
```
matrix@docker:~$ ls -l synapse
total 16
-rw-r--r-- 1 100999 100999 1281 Apr 24 15:02 homeserver.yaml
drwxr-xr-x 2 matrix matrix 4096 Apr 24 15:02 logs
-rw-r--r-- 1 matrix matrix  729 Apr 24 15:17 mydomain.com.log.config
-rw-r----- 1 100999 100999   59 Apr 24 15:02 mydomain.com.signing.key
```
So I could edit the mydomain.com.log.config, but not homeserver.yaml, with the user "matrix"

This is on a proxmox KVM Machine, with snapshots, so I can go back a step to just before I started the install.
If you are interested, I can try different things you suggest without losing much time on both sides.

**Comment by knurd75zid** [comment]
adding user: "1000:1000" to the synapse docker in docker-compose.yml did not work. 
I get this error then:
```
Creating log config /data/mydomain.com.log.config                                                                                    Traceback (most recent call last):                                                                                                     File "/start.py", line 285, in <module>                                                                                                main(sys.argv, os.environ)
  File "/start.py", line 215, in main
    return run_generate_config(environ, ownership)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/start.py", line 167, in run_generate_config
    convert("/conf/log.config", log_config_file, environ)
  File "/start.py", line 40, in convert
    with open(dst, "w") as outfile:
```

**Comment by tcpipuk** [comment]
Have you had any success identifying the problem? Did you want me to make any changes to accommodate your particular setup?

**Comment by tcpipuk** [comment]
No response in months, I'm assuming this was a local issue.
