### ISSUE TITLE
Update reverse proxy config for the new federated media worker endpoints

### ISSUE THREAD

**Issue by vincejv** [tcpipuk/tcpipuk.github.io#18]
See: https://github.com/element-hq/synapse/pull/17421

[New worker endpoints for authenticated client and federation media](https://element-hq.github.io/synapse/v1.111/upgrade.html#new-worker-endpoints-for-authenticated-client-and-federation-media)
[Media repository workers](https://element-hq.github.io/synapse/v1.111/workers.html#synapseappmedia_repository) handling Media APIs can now handle the following endpoint patterns:

```
^/_matrix/client/v1/media/.*$
^/_matrix/federation/v1/media/.*$
```
Please update your reverse proxy configuration.

**Comment by tcpipuk** [comment]
Thanks for raising that - I've added https://github.com/tcpipuk/tcpipuk.github.io/commit/4ba4ab9b8cc56e6ea4aad71e6bd4a28b0a0c4050 to accommodate these endpoints! 👍

**Comment by tcpipuk** [comment]
Thanks for raising that - I've added https://github.com/tcpipuk/tcpipuk.github.io/commit/4ba4ab9b8cc56e6ea4aad71e6bd4a28b0a0c4050 to accommodate these endpoints! 👍
